### ISSUE TITLE
Content not descriptive in README.md

### ISSUE THREAD

**Issue by Rakesh-97** [vishichoudhary/studentResumeManagementApplication#1]
Hi,
I have been looking over the code in the repository, and found the content bit irrelevant and misleading.
Please provide proper details in README.md

you may take help from https://medium.com/@meakaakka/a-beginners-guide-to-writing-a-kickass-readme-7ac01da88ab3

Regards
spider

**Comment by vishichoudhary** [comment]
why were you looking at our code?

**Comment by nimitbhardwaj** [comment]
Foolish people should stop thinking. Im telling this to you spider

**Comment by sasuke29** [comment]
Thank you @Spider34 
We'll try to take your advice into consideration.

**Comment by Souravirus** [comment]
I guess @spider34 is right. Please improve the README.md rather than replying manerlessly

**Comment by Souravirus** [comment]
I think you should be more open to first time contributers

**Comment by sunidhichaudhary** [comment]
Thanks to @ Spider34 and @Souravirus 
We'll try to take your advice into consideration.
